# <font color='green'> Tipos y estructuras de datos (Parte I)</font>

## <font color='green'>Listas</font>

### <font color='green'>Creación y acceso</font>

In [ ]:
# Creación de la lista con frutas favoritas
frutas_favoritas = ['manzana', 'banana', 'uva', 'fresa']

# Preguntar al usuario por una fruta y agregarla a la lista
nueva_fruta = input("Agrega una fruta a la lista: ")
frutas_favoritas.append(nueva_fruta)

# Mostrar la lista completa
print("Lista de frutas favoritas:")
for fruta in frutas_favoritas:
    print("-", fruta)

Agrega una fruta a la lista: durazno
Lista de frutas favoritas:
- manzana
- banana
- uva
- fresa
- durazno

### <font color='green'>Filtrado</font>

In [ ]:
# Crear una lista con los nombres de tus amigos
amigos = ['Ana', 'Carlos', 'Luis', 'María', 'Pedro', 'Patricia']

# Pedir al usuario que ingrese una letra
letra = input("Ingresa una letra: ")

# Filtrar los nombres que comienzan con la letra ingresada. Notar que se pasa a minúscula
filtrados = [amigo for amigo in amigos if amigo.lower().startswith(letra.lower())]

# Mostrar los nombres filtrados
print("Nombres que comienzan con la letra", letra + ":")
for amigo in filtrados:
    print("-", amigo)

Ingresa una letra: a
Nombres que comienzan con la letra a:
- Ana

### <font color='green'>Manipulación de listas</font>

In [ ]:
# Crea una lista con tus películas favoritas
peliculas_favoritas = ["El Padrino", "Titanic", "El Señor de los Anillos", "La Cenicienta"]

# Pide al usuario que agregue una película nueva a la lista
nueva_pelicula = input("Por favor, escribe el nombre de una nueva película que quieras agregar a la lista: ")
peliculas_favoritas.append(nueva_pelicula)

# Pide al usuario que elimine una película existente de la lista
pelicula_a_eliminar = input("Por favor, escribe el nombre de una película que quieras eliminar de la lista: ")
peliculas_favoritas.remove(pelicula_a_eliminar)

# Muestra la lista completa actualizada
print("Esta es tu lista de películas favoritas actualizada:")
for pelicula in peliculas_favoritas:
    print("-", pelicula)

Por favor, escribe el nombre de una nueva película que quieras agregar a la lista: Rocky
Por favor, escribe el nombre de una película que quieras eliminar de la lista: Titanic
Esta es tu lista de películas favoritas actualizada:
- El Padrino
- El Señor de los Anillos
- La Cenicienta
- Rocky

### <font color='green'>Ordenando una lista</font>

In [ ]:
# Ordenar una lista
libros_favoritos = ["1984", "El Gran Gatsby", "Cien años de soledad", "Orgullo y prejuicio"]

# Ordena la lista alfabéticamente
libros_favoritos.sort()

# Muestra los libros en orden ascendente
print("Esta es tu lista de libros favoritos en orden alfabético:")
for libro in libros_favoritos:
    print(libro)

Esta es tu lista de libros favoritos en orden alfabético:
1984
Cien años de soledad
El Gran Gatsby
Orgullo y prejuicio

## <font color='green'>Diccionarios</font>

### <font color='green'>Creación y acceso</font>

In [ ]:
# Creación
mi_diccionario = {'nombre': 'Juan', 'edad': 30, 'ciudad': 'Lima'}
print(mi_diccionario['nombre'])  # salida: 'Juan'
print(mi_diccionario['edad'])  # salida: 30

# Crea un diccionario con los nombres de tus amigos y la ciudad donde viven
amigos = {"Juan": "Bogotá", "Maria": "Medellín", "Luis": "Cali", "Ana": "Barranquilla"}

# Pide al usuario que agregue un amigo nuevo y la ciudad donde vive
nuevo_amigo = input("Por favor, escribe el nombre de un nuevo amigo: ")
ciudad_nuevo_amigo = input("Por favor, escribe la ciudad donde vive el nuevo amigo: ")
amigos[nuevo_amigo] = ciudad_nuevo_amigo

# Muestra el diccionario completo
print("Este es tu diccionario de amigos y ciudades:")
for amigo, ciudad in amigos.items():
    print(f"- {amigo} vive en {ciudad}")

Juan
30
Por favor, escribe el nombre de un nuevo amigo: Lucas
Por favor, escribe la ciudad donde vive el nuevo amigo: Buenos Aires
Este es tu diccionario de amigos y ciudades:
- Juan vive en Bogotá
- Maria vive en Medellín
- Luis vive en Cali
- Ana vive en Barranquilla
- Lucas vive en Buenos Aires

### <font color='green'>Filtrado</font>

In [ ]:
# Crea un diccionario con los nombres de tus amigos y su edad
amigos_edades = {"Juan": 25, "Maria": 30, "Luis": 25, "Ana": 27}

# Pide al usuario que ingrese una edad
edad_buscar = int(input("Por favor, escribe una edad para buscar amigos que tengan esa edad: "))

# Muestra los nombres de los amigos que tienen la edad buscada
print(f"Amigos que tienen {edad_buscar} años:")
for amigo, edad in amigos_edades.items():
    if edad == edad_buscar:
        print("-", amigo)

Por favor, escribe una edad para buscar amigos que tengan esa edad: 25
Amigos que tienen 25 años:
- Juan
- Luis

### <font color='green'>Manipulación</font>

In [ ]:
# Crea un diccionario con los nombres de tus películas favoritas y su año de lanzamiento
peliculas = {"El Padrino": 1972, "Pulp Fiction": 1994, "El Rey León": 1994, "Titanic": 1997}

# Pide al usuario que agregue una película nueva con su año de lanzamiento
nueva_pelicula = input("Por favor, escribe el nombre de una nueva película: ")
anio_nueva_pelicula = int(input("Por favor, escribe el año de lanzamiento de la nueva película: "))
peliculas[nueva_pelicula] = anio_nueva_pelicula

# Pide al usuario que elimine una película existente
pelicula_eliminar = input("Por favor, escribe el nombre de una película para eliminarla: ")
del peliculas[pelicula_eliminar]

# Muestra el diccionario completo actualizado
print("Este es tu diccionario de películas actualizado y años de lanzamiento:")
for pelicula, anio in peliculas.items():
    print(f"- {pelicula} se lanzó en {anio}")

Por favor, escribe el nombre de una nueva película: El señor de los anillos
Por favor, escribe el año de lanzamiento de la nueva película: 2003
Por favor, escribe el nombre de una película para eliminarla: El Rey León
Este es tu diccionario de películas actualizado y años de lanzamiento:
- El Padrino se lanzó en 1972
- Pulp Fiction se lanzó en 1994
- Titanic se lanzó en 1997
- El señor de los anillos se lanzó en 2003

### <font color='green'>Orden</font>

In [ ]:
# Crea un diccionario con los nombres de tus libros favoritos y su autor
libros = {"El Quijote": "Miguel de Cervantes", "Cien años de soledad": "Gabriel García Márquez", "La Iliada": "Homero", "Orgullo y prejuicio": "Jane Austen"}

# Ordena el diccionario alfabéticamente por el nombre del libro
libros_ordenados = dict(sorted(libros.items()))

# Muestra los libros en orden ascendente
print("Estos son tus libros favoritos ordenados alfabéticamente:")
for libro, autor in libros_ordenados.items():
    print(f"- {libro}, escrito por {autor}")

Estos son tus libros favoritos ordenados alfabéticamente:
- Cien años de soledad, escrito por Gabriel García Márquez
- El Quijote, escrito por Miguel de Cervantes
- La Iliada, escrito por Homero
- Orgullo y prejuicio, escrito por Jane Austen

### <font color='green'>Listas y diccionarios</font>

Para transformar de listas a diccionarios en Python, puedes usar la función **zip()**, que combina dos listas en pares de valores. Luego deberás convertir el objeto zip en una **lista** o un **diccionario** utilizando las funciones **list()** o **dict()**, respectivamente. Por ejemplo:

In [ ]:
nombres = ["Juan", "María", "Pedro"]
edades = [28, 30, 25]

diccionario_edades = dict(zip(nombres, edades))

print(diccionario_edades)

{'Juan': 28, 'María': 30, 'Pedro': 25}

Para transformar de **diccionarios** a **listas**, puedes usar los métodos **keys()** y **values()**.
Por ejemplo:

In [ ]:
diccionario_edades = {'Juan': 28, 'María': 30, 'Pedro': 25}

nombres = list(diccionario_edades.keys())
edades = list(diccionario_edades.values())

print(nombres)
print(edades)

['Juan', 'María', 'Pedro']
[28, 30, 25]

Como vemos en estos ejemplos, para transformar de **diccionario** a **lista** obtendremos o las llaves o los valores del diccionario.

Por otro lado para transformar de **lista** a **diccionario** debemos pasarle pares llave-valor o **tuplas** para adaptar la estructura a la de un **diccionario.**

## <font color='green'>Tuplas</font>

Las tuplas en Python son estructuras de datos similares a las listas, pero a diferencia de ellas son **inmutables,** es decir, una vez creadas no se pueden modificar.

Para crear una tupla en Python se utiliza una sintaxis similar a la de las listas, pero en lugar de corchetes, se utilizan paréntesis.

In [ ]:
mi_tupla=(1,2,3,4)
print(mi_tupla[3])

4

In [ ]:
# ¡Aquí tendremos un error!
mi_tupla[1]=6
print(mi_tupla)

TypeError: 'tuple' object does not support item assignment

## <font color='green'>Sets</font>

Los **sets** en Python son una estructura de datos que permite almacenar elementos únicos e inmutables en un conjunto sin orden. Una gran ventaja de los sets es **la eliminación de elementos duplicados de una lista.**

In [ ]:
my_set = set([1, 2, 3, 3, 3, 3])
print(my_set)

{1, 2, 3}

FIN DE LA PRIMERA CLASE (PUEDE BORRAR ESTA CELDA)

# <font color='green'>NumPy Arrays </font>

Los **NumPy Arrays** son una estructura de datos más eficiente que las **listas** y **diccionarios** para manejar grandes cantidades de datos numéricos, como números enteros y flotantes., Para ello, cuentan con funciones integradas para realizar operaciones matemáticas en matrices y vectores de manera eficiente.

## <font color='green'>Instalación</font>

Para usar **NumPy** y **arrays** en Python, primero debes asegurarte de tener **NumPy** instalado en tu entorno de Python.

- Puedes instalarlo usando un administrador de paquetes de Python como **pip**: ```pip install numpy```

## <font color='green'>Operaciones con NumPy arrays</font>

### <font color='green'>Operaciones vectorizadas</font>

In [ ]:
import numpy as np

lista = [0, 1, 2, 3, 4]
my_array = np.array(lista)

print(my_array)

[0 1 2 3 4]

In [ ]:
lista1 = [1,2,3]
lista2 = [10,20,30]
lista3 = [100, 200, 300]

array1 = np.array(lista1)
array2 = np.array(lista2)
array3 = np.array(lista3)

In [ ]:
lista1 + lista2 + lista3

[1, 2, 3, 10, 20, 30, 100, 200, 300]

In [ ]:
array1 + array2 + array3

array([111, 222, 333])

In [ ]:
array1*array2

array([10, 40, 90])

In [ ]:
array1/array2

array([0.1, 0.1, 0.1])

In [ ]:
2*lista1

[1, 2, 3, 1, 2, 3]

In [ ]:
2*array1

array([2, 4, 6])

### <font color='green'>Filtrado</font>

In [ ]:
import numpy as np

lista = [1, 6, 3, 8, 2, 9,10]

arr = np.array(lista)

arr[arr > 5]

array([ 6,  8,  9, 10])

Para filtrar un array por más de una condición, se puede combinar las condiciones utilizando las funciones:
- **numpy.logical_and().**
- **numpy.logical_or().**

Por ejemplo, si tenemos un arreglo de números aleatorios y queremos filtrar los valores que sean mayores a 5 y menores a 10, podemos hacer lo siguiente:

In [ ]:
arr[np.logical_and(arr > 5, arr < 10)]

array([6, 8, 9])

### <font color='green'>Otros métodos</font>

- **np.zeros():** Crea un array de ceros con la forma especificada.
- **np.ones():** Crea un array de unos con la forma especificada.
- **np.arange():** Crea un array con valores espaciados uniformemente en un intervalo especificado.
- **np.linspace():** Crea un array con valores espaciados uniformemente en un rango especificado.

In [ ]:
a=np.zeros(3)
b=np.ones(3)
c=np.arange(2,30,5)#inicio, fin, distancia entre valores
d=np.linspace(2,3,5)#inicio, fin, cantidad de valores
print(a)
print(b)
print(c)
print(d)

[0. 0. 0.]
[1. 1. 1.]
[ 2  7 12 17 22 27]
[2.   2.25 2.5  2.75 3.  ]

FIN DE LA SEGUNDA CLASE (PUEDE BORRAR ESTA CELDA)

---



---



---

## <font color='green'>Manejo de datos con NumPy Arrays</font>

### <font color='green'>Carga de datos con loadtxt</font>

In [ ]:
nombres = np.loadtxt("nombre_astronautas.csv", delimiter=',', dtype=str, encoding='utf-8')

Los argumentos que se pasan a la función son los siguientes:

- **nombre_astronautas.csv:** este es el nombre del archivo que se desea cargar.

- **delimiter:** este argumento indica que el delimitador utilizado en el archivo es la coma (','). Es decir, cada valor en el archivo está separado por comas.

- **dtype:** este argumento indica que se desea cargar los datos como cadenas de texto (strings).

- **encoding:** este argumento indica que el archivo está codificado en UTF-8. UTF-8 es un tipo de codificación de caracteres que permite representar la mayoría de los caracteres utilizados en el mundo.

Adiiconalmente, podemos utilizar alguns otros parámetros optativos que nos serán útiles para la carga de archivos separados por coma, como los **csv*:

- **skiprows:** Con este parámetro puedes indicar el número de filas que quieres saltar al leer el archivo. Esto es útil si el archivo tiene filas de encabezado que no contienen datos, por ejemplo.

- **usecols:** Este parámetro te permite seleccionar las columnas que quieres leer del archivo. Puedes pasarle un número de columna (empezando por cero) o una lista de números si necesitas leer varias columnas.

Por ejemplo, supongamos que tenemos un archivo de datos separados por comas:
a,	b,	c,	d<br>
1,	4,	6,	2<br>
2,	5,	4,	1<br>
3,	4,	9,	7<br>
4,	8,	0,	3<br>
5,	6,	9,	9<br>
6,	23,	87,	3<br>
7,	8,	6,	75<br>
8,	5,	4,	53<br>
9,	9,	2,	43<br>
10,	6,	2,	3<br>

Utilizamos los parámetros del método loadtxt() para indicar que el archivo tiene separación por comas, también indicamos que solo considere las columnas 1 y 2,  y también que se salte la fila que tiene los encabezados.

In [ ]:
datos = np.loadtxt('datos.csv', delimiter=',', skiprows=1, usecols=(1, 2), dtype=int)
print(datos)

[[ 4  6]
 [ 5  4]
 [ 4  9]
 [ 8  0]
 [ 6  9]
 [23 87]
 [ 8  6]
 [ 5  4]
 [ 9  2]
 [ 6  2]]

### <font color='green'>Estadísticas con NumPy Arrays</font>

In [ ]:
valores = np.array([5,2,7,3,7,4,8,4,2,5,8,4,7,4,7,9,0,5,3,3])
print(np.mean(valores))#Calcula la media de los elementos del array.
print(np.median(valores))#Calcula la mediana de los elementos del array.
print(np.std(valores))#Calcula la desviación estándar de los elementos del array.
print(np.var(valores))#Calcula la varianza de los elementos del array.
print(np.percentile(valores,75))#Calcula el percentil 75 de los elementos del array.

4.85
4.5
2.329699551444349
5.4275
7.0

FIN DE LA TERCERA CLASE (PUEDE BORRAR ESTA CELDA)

# <font color='green'>Pandas DataFrames</font>

## <font color='green'>Creación</font>

In [ ]:
# Una lista de diccionarios.
import pandas as pd

lista_de_diccionarios = [

    {'nombre': 'Ana', 'profesion': 'guitarra', 'edad': '34'},
    {'nombre': 'Luis', 'profesion': 'fotógrafo', 'edad': '27'},
    {'nombre': 'María', 'profesion': 'profesora', 'edad': '42'},
    {'nombre': 'Pedro', 'profesion': 'chef', 'edad': '39'},
    {'nombre': 'Isabel', 'profesion': 'arquitecta', 'edad': '29'},
    {'nombre': 'Sergio', 'profesion': 'músico', 'edad': '25'},
    {'nombre': 'Carla', 'profesion': 'ingeniera', 'edad': '31'},
    {'nombre': 'David', 'profesion': 'estudiante', 'edad': '20'},
    {'nombre': 'Lucía', 'profesion': 'abogada', 'edad': '36'},
    {'nombre': 'Jorge', 'profesion': 'actor', 'edad': '28'}

]

df = pd.DataFrame(lista_de_diccionarios)
df

   nombre   profesion edad
0     Ana    guitarra   34
1    Luis   fotógrafo   27
2   María   profesora   42
3   Pedro        chef   39
4  Isabel  arquitecta   29
5  Sergio      músico   25
6   Carla   ingeniera   31
7   David  estudiante   20
8   Lucía     abogada   36
9   Jorge       actor   28

In [ ]:
# Una lista de listas. (listas anidadas):

lista_anidada = [

    ['Ana', 'guitarra', '34'],
    ['Luis', 'fotógrafo', '27'],
    ['María', 'profesora', '42'],
    ['Pedro', 'chef', '39'],
    ['Isabel', 'arquitecta', '29'],
    ['Sergio', 'músico', '25'],
    ['Carla', 'ingeniera', '31'],
    ['David', 'estudiante', '20'],
    ['Lucía', 'abogada', '36'],
    ['Jorge', 'actor', '28']
]


df = pd.DataFrame(lista_anidada, columns = ['nombre', 'profesion', 'edad'])
df

   nombre   profesion edad
0     Ana    guitarra   34
1    Luis   fotógrafo   27
2   María   profesora   42
3   Pedro        chef   39
4  Isabel  arquitecta   29
5  Sergio      músico   25
6   Carla   ingeniera   31
7   David  estudiante   20
8   Lucía     abogada   36
9   Jorge       actor   28

## <font color='green'>Carga desde fuentes externas</font>

In [ ]:
import pandas as pd

df = pd.read_excel("resumen_resultados_astronautas.xlsx")
df.head(10)

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica
0,Alana Morillo,32,75,180,93,88,78,89,6,Si
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si
2,Sofía Puig,29,80,185,85,80,90,91,3,Si
3,Valentina Tasis,30,65,175,90,91,85,92,2,No
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si
5,Amaya de la Cruz,26,64,170,80,94,79,86,4,No
6,María Juderías,28,78,182,88,85,87,92,5,Si
7,Perla Alcocer,30,71,168,86,92,82,88,3,No
8,Consuela Arboleda,33,77,188,94,83,89,93,8,Si
9,María José Franco,29,70,175,87,90,80,89,2,No

In [ ]:
df_venta_rosquillas = pd.read_csv("donut_lab_sales.csv", delimiter = ',')
df_venta_rosquillas.head(5)

                  rosquilla  cantidad
0       Rosquilla de Filete        52
1        Rosquilla de Tacos        12
2          Rosquilla de Uva        62
3  Rosquilla de Champiñones        90
4        Rosquilla de Carne        22

In [ ]:
df_info_nutricional = pd.read_pickle("info_nutricional_rosquillas.pkl")
df_info_nutricional.head(5)

,Tipo de Rosquilla,Puntuación,Calorías,Grasas (g),Proteínas (g),Carbohidratos (g),Azúcar (g)
0,Queso,75,320,16,4,38,22
1,Hamburguesa,65,290,14,3,36,18
2,Carne,63,310,15,3,38,20
3,Miel,61,280,13,2,36,21
4,Uva,60,250,12,2,32,18